<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename='inertial_macros.xacro'/>


    <xacro:macro name="wheel" params="position radius thickness mass">
        <link name="${position}_wheel">
            <collision>
                <origin xyz="0 0 ${thickness/2}"/>
                <geometry>
                    <cylinder radius="${radius}" length="${thickness}"/>
                </geometry>
                <material name="blue"/>
            </collision>

            <visual>
                <origin xyz="0 0 ${wheel_thickness/2}"/>
                <geometry>
                    <cylinder radius="${radius}" length="${thickness}"/>
                </geometry>
            </visual>

            <xacro:inertial_cylinder mass="${mass}" length="${thickness}" radius="${radius}">
                <origin xyz="0 0 ${wheel_thickness/2}"/>
            </xacro:inertial_cylinder>
        </link>

        <gazebo reference="${position}_wheel">
            <material>Gazebo/Blue</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="wheel_joint" params="position bot_center_to_wheel_center_x bot_center_to_wheel_center_y">
        <joint name="${position}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${position}_wheel"/>
            <axis xyz="0 0 1"/>

            <xacro:if value="${position.beginswith('front')}">
                <xacro:property name="x_sign" value="1"/>
            </xacro:if>
            <xacro:unless value="${position.beginswith('front')}">
                <xacro:property name="x_sign" value="-1"/>
            </xacro:unless>
            <xacro:if value="${position.endswith('left')}">
                <xacro:property name="y_sign" value="1"/>
            </xacro:if>
            <xacro:unless value="${position.endswith('left')}">
                <xacro:property name="y_sign" value="-1"/>
            </xacro:unless>

            <origin xyz="${x_sign * bot_center_to_wheel_center_x} ${y_sign * bot_center_to_wheel_center_y} 0" rpy="-${pi/2} 0 0"/>
            
        </joint>
    </xacro:macro>
    
</robot>